### ISSUE TITLE
What is ext_begin_date and ext_end_date?

### ISSUE THREAD

**Issue by jqnatividad** [MandanaMoshref/ckanext-datesearch#1]
Hi @MandanaMoshref ,
Thanks for sharing this plugin.

I'm currently trying to use it and I've added begin-collection_date and end-collection_date to my scheming schema.

However, I don't understand where ext_begin_date and ext_end_date fits in.  Do I also need to define them in my schema?

**Comment by MandanaMoshref** [comment]
Sorry, I am quite overloaded with other tasks...that's why it took me long to answer you:

> I'm currently trying to use it and I've added begin-collection_date and end-collection_date to my scheming schema.
> 
One suggestion replace "-" with "_" between begin/end and collection. It will cause syntax errors when you want to use python... (my bad)
> However, I don't understand where ext_begin_date and ext_end_date fits in. Do I also need to define them in my schema?

As far as I remember, these two are for the slider in the search page.... would that make sense? if not I have to look at the code again...
